spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  application:
    name: esl_interface
  jackson:
    time-zone: Asia/Seoul
  data:
    mongodb:
      host: 10.253.22.112
      port: 27017
      user: esl_interface
      password: 0hTQos3g+cJjNglMAOGzQg==
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    password: oracle
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  ssg-depart-datasource:
    hikari:
      jdbc-url: jdbc:postgresql://127.0.0.1:9010/ssg_depart
      driver-class-name: org.postgresql.Driver
      data-source-properties:
        user: ssg_depart
        password: "!2ssg_depart#4"

api:
  url: https://192.168.0.10:9002/
  store: TEST001
  company: TEST001

file:
  path: /app/esl_if/daily/
