spring:
  docker:
    compose:
      enabled: false
  config:
    activate:
      on-profile: local
  main:
    allow-bean-definition-overriding: true
  application:
    name: esl_interface
  jackson:
    time-zone: Asia/Seoul
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://192.168.10.244:3306/shinsegaesl
      driver-class-name: org.mariadb.jdbc.Driver
      username: aims
      password: aims
  aims-core-datasource:
    hikari:
      jdbc-url: jdbc:postgresql://192.168.10.170:9010/AIMS_CORE_DB
      driver-class-name: org.postgresql.Driver
      data-source-properties:
        user: aims
        password: aims
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 18082
  schedule:
    receiveTetpluEsl.cron: 0 */10 * * * *
    receiveVTetrplEsl.cron: 0 */5 * * * *

api:
  url: https://192.168.10.170:9002/
  store: 1
  company: TEST001

file:
  path: C:/eslproject/shinsega/esl_interface_etl_250505_02/src/main/resources/file/
  columns: STORE_CODE,PLU_CODE,PRICE_SECT,START_DATE,END_DATE,MD_CODE,PUM_CODE,EVENT_SECT,CLASS_CODE,PLU_NAME,CURR_SAL_PRICE,GOODS_SECT,MG_RATE,TAX_FLAG,SYS_DATE,SYS_TIME,ORIGIN_NAME,NOR_SAL_PRICE,CONTENTS_QTY,DISPLAY_UNIT_NAME,DISPLAY_UNIT_QTY,DEAL_GUBN,ORIGIN_CODE,BRAND_NAME,CATE_CODE,CATE_NAME,MOD_DATE,MOD_TIME,MOD_EMPNO,IF_DATE,IF_TIME,IF_EMPNO,DISPLAY_UNIT_PRICE,SELLNG_PNT,GOOS_AUTH_IMG,WINE_SUGR_CONT,WINE_BODY,WINE_KIND,WINE_EVAL_1,WINE_EVAL_2,WINE_EVAL_3,WINE_PLOR,WINE_ITEM_KIND,WINE_VINT,MOBL_CUP_GOOS_YN,LAYOUT_GUBN_1,LAYOUT_GUBN_2,QR_CODE,CONTENTS_QTY_UNIT,COMBINE_DISPLAY_UNIT_PRICE,DISPLAY_TYPE,GOOS_INFO1,GOOS_INFO2

logging:
  level:
    root: info
    com.multiply.esl_interface: debug
aims:
  ip: 192.168.10.170
  user: aims
  password: semco150
